const BASE = "/sprites/ingredients";

const SPRITE_MAP: Record<string, string> = {
  // Ingredients
  "Apple":              `${BASE}/apple.png`,
  "Avocado":            `${BASE}/avocado.png`,
  "Bacon":              `${BASE}/bacon.png`,
  "Banana":             `${BASE}/banana.png`,
  "Basil":              `${BASE}/basil.png`,
  "Butter":             `${BASE}/butter.png`,
  "Cheese":             `${BASE}/cheese.png`,
  "Cherry Tomatoes":    `${BASE}/cherrytomatoes.png`,
  "Cherry Tomato":      `${BASE}/cherrytomatoes.png`,
  "Chorizo":            `${BASE}/chorizo.png`,
  "Cream Cheese":       `${BASE}/creamcheese.png`,
  "Cucumber":           `${BASE}/cucumber.png`,
  "Egg":                `${BASE}/egg.png`,
  "Fried Fillet":       `${BASE}/friedfillet.png`,
  "Green Bell Pepper":  `${BASE}/greenbellpepper.png`,
  "Green Pepper":       `${BASE}/greenbellpepper.png`,
  "Ham":                `${BASE}/ham.png`,
  "Hamburger":          `${BASE}/hamburger.png`,
  "Herbed Sausage":     `${BASE}/herbedsausage.png`,
  "Horseradish":        `${BASE}/horseradish.png`,
  "Jalapeno":           `${BASE}/jalapeno.png`,
  "Jam":                `${BASE}/jam.png`,
  "Kiwi":               `${BASE}/kiwi.png`,
  "Klawf Stick":        `${BASE}/klawfstick.png`,
  "Lettuce":            `${BASE}/lettuce.png`,
  "Noodles":            `${BASE}/noodles.png`,
  "Onion":              `${BASE}/onion.png`,
  "Pickle":             `${BASE}/pickle.png`,
  "Pineapple":          `${BASE}/pineapple.png`,
  "Potato Salad":       `${BASE}/potatosalad.png`,
  "Potato Tortilla":    `${BASE}/potatotortilla.png`,
  "Prosciutto":         `${BASE}/prosciutto.png`,
  "Red Bell Pepper":    `${BASE}/redbellpepper.png`,
  "Red Pepper":         `${BASE}/redbellpepper.png`,
  "Red Onion":          `${BASE}/redonion.png`,
  "Rice":               `${BASE}/rice.png`,
  "Smoked Fillet":      `${BASE}/smokedfillet.png`,
  "Strawberry":         `${BASE}/strawberry.png`,
  "Tofu":               `${BASE}/tofu.png`,
  "Tomato":             `${BASE}/tomato.png`,
  "Watercress":         `${BASE}/watercress.png`,
  "Whipped Cream":      `${BASE}/whippedcream.png`,
  "Yellow Bell Pepper": `${BASE}/yellowbellpepper.png`,
  "Yellow Pepper":      `${BASE}/yellowbellpepper.png`,
  // Condiments
  "Chili Sauce":        `${BASE}/chilisauce.png`,
  "Curry Powder":       `${BASE}/currypowder.png`,
  "Ketchup":            `${BASE}/ketchup.png`,
  "Marmalade":          `${BASE}/marmalade.png`,
  "Mayonnaise":         `${BASE}/mayonnaise.png`,
  "Mustard":            `${BASE}/mustard.png`,
  "Olive Oil":          `${BASE}/oliveoil.png`,
  "Peanut Butter":      `${BASE}/peanutbutter.png`,
  "Pepper":             `${BASE}/pepper.png`,
  "Salt":               `${BASE}/salt.png`,
  "Vinegar":            `${BASE}/vinegar.png`,
  "Wasabi":             `${BASE}/wasabi.png`,
  "Yogurt":             `${BASE}/yogurt.png`,
  // Herba Mystica
  "Sweet Herba Mystica":  `${BASE}/sweetherbamystica.png`,
  "Salty Herba Mystica":  `${BASE}/saltyherbamystica.png`,
  "Sour Herba Mystica":   `${BASE}/sourherbamystica.png`,
  "Bitter Herba Mystica": `${BASE}/bitterherbamystica.png`,
  "Spicy Herba Mystica":  `${BASE}/spicyherbamystica.png`,
};

export function getIngredientSprite(name: string): string | null {
  return SPRITE_MAP[name] ?? null;
}
